#!/usr/bin/env python3
"""
Turn a letter-lab export into js/styles.js.

    python3 tools/make_styles.py path/to/microdose-letters.json

Uses only the Python standard library. Every stroke that has a letter assigned (M, I, C, R, O, D, O, S, E)
is included; strokes left unassigned or marked "skip" are left out. Each version's pen colour (pink, blue or
red) is worked out from the ink colour the extraction script recorded; versions with none count as pink.

Afterwards, add a line for each new version in js/config.js under `credits`, naming who drew it.
"""
import json
import pathlib
import sys


def pen(ink):
    if not ink:
        return "pink"
    r, g, b = (int(ink[i:i + 2], 16) for i in (1, 3, 5))
    return "red" if r > b else "blue"


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    data = json.load(open(sys.argv[1]))
    out = pathlib.Path(__file__).resolve().parent.parent / "js" / "styles.js"
    lines, ids = [], []
    for w in data["words"]:
        strokes = [[s["d"], s["letter"]] for s in w["strokes"] if isinstance(s.get("letter"), int) and 0 <= s["letter"] <= 8]
        if not strokes:
            print(f"skipping {w['id']} ({w.get('name', '')}): no letters assigned")
            continue
        lines.append(json.dumps({"id": w["id"], "pen": pen(w.get("ink")), "s": strokes}, separators=(",", ":")))
        ids.append(w["id"])
    header = (
        "/* The lettering: every version of the title as pen strokes, grouped by letter ([path, letter 0-8]).\n"
        "   Generated by tools/make_styles.py from a letter-lab export. Please don't edit by hand. */\n"
    )
    out.write_text(header + "window.MICRODOSE_STYLES = [\n" + ",\n".join(lines) + "\n];\n")
    print(f"wrote {out} with {len(ids)} versions:\n  " + ", ".join(ids))
    print("Now add a credit for each new id in js/config.js.")


if __name__ == "__main__":
    main()
